
package com.msbank.Backend.PD;

/**
 *ALL VARIABLES, SETTERS, GETTERS & TOSTRING() NEEDED FOR THE APPLICATION TO FUNCTION PROPERLY
 *MOST VARIABLES WILL BE USER INPUT & ALSO GENERATED BY SYSTEM ITSELF
 *PROBLEM DOMAIN
 *
 * 
 * @author Mcacisi Sithole
 */

public class BankPD {
    
    private String fullname;
    private String idNumber;
    private String contact;
    private String gender;
    private String email;
    private String address;
    private String city;
    private String nationality;
    private String accountNumber;
    
    
    
    
    
    public BankPD(){
        fullname = "";
        idNumber = "";
        contact = "";
        gender = "";
        email = "";
        address = "";
        city = "";
        nationality = "";
        accountNumber = "";
    }

    
    
    
    
    public BankPD(String fullname, String idNumber, String contact, String gender, String email, String address, String city, String nationality, String accountNumber) {
        this.fullname = fullname;
        this.idNumber = idNumber;
        this.contact = contact;
        this.gender = gender;
        this.email = email;
        this.address = address;
        this.city = city;
        this.nationality = nationality;
        this.accountNumber = accountNumber;
    }

    
    
    
    
    public String getFullname() {
        return fullname;
    }

    public String getIdNumber() {
        return idNumber;
    }

    public String getContact() {
        return contact;
    }

    public String getGender() {
        return gender;
    }

    public String getEmail() {
        return email;
    }

    public String getAddress() {
        return address;
    }

    public String getCity() {
        return city;
    }

    public String getNationality() {
        return nationality;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    
    
    
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    
    
    
    
    @Override
    public String toString() {
        return "FULLNAME: " + fullname + "\n" +
               "ID NUMBER: " + idNumber + "\n" +
               "CONTACT: " + contact + "\n" +
               "GENDER: " + gender + "\n" +
               "EMAIL: " + email + "\n" +
               "ADDRESS: " + address + "\n" +
               "CITY: " + city + "\n" +
               "NATIONALITY: " + nationality + "\n" +
               "SAVINGS ACCOUNT NO: " + accountNumber;
    }
    
    
    
}
